### ISSUE TITLE
SVGButton not available for the null toolkit

### ISSUE THREAD

**Issue by fnoble** [enthought/enable#162]
We have some code that can run either graphically or in the terminal and importing the SVGButton editor is causing problems.

Seems like it would be straightforward to provide a simple mock for this in the null toolkit.

```
Traceback (most recent call last):
  File "./print_device_details.py", line 7, in <module>
    import settings_view
  File "/home/fnoble/piksi_firmware/scripts/testing/../settings_view.py", line 15, in <module>
    from enable.savage.trait_defs.ui.svg_button import SVGButton
  File "/usr/lib/python2.7/dist-packages/enable/savage/trait_defs/ui/svg_button.py", line 19, in <module>
    from svg_button_editor import SVGButtonEditor
  File "/usr/lib/python2.7/dist-packages/enable/savage/trait_defs/ui/svg_button_editor.py", line 22, in <module>
    from enable.savage.trait_defs.ui.toolkit import toolkit_object
  File "/usr/lib/python2.7/dist-packages/enable/savage/trait_defs/ui/toolkit.py", line 43, in <module>
    _init_toolkit()
  File "/usr/lib/python2.7/dist-packages/enable/savage/trait_defs/ui/toolkit.py", line 36, in _init_toolkit
    "toolkit." % ETSConfig.toolkit
ImportError: Unable to import a Savage backend for the null toolkit.
```

**Comment by makslevental** [comment]
in 2019 i still have this error. can someone explain to me what the hell this is?
