### ISSUE TITLE
kiva/agg/tests/test_save.py fails

### ISSUE THREAD

**Issue by jwiggins** [enthought/enable#17]
-> pwd
    /home/ischnell/ets/ETS_3.0.0b1/Enable_3.0.0b1/enthought/kiva/agg/tests
    -> nosetests test_save.py 
    FF..
    ======================================================================
    FAIL: test_bgr24_format (test_save.TestSave)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/ischnell/ets/ETS_3.0.0b1/Enable_3.0.0b1/enthought/kiva/agg/tests/test_save.py", line 21, in test_bgr24_format
        self.do_check_format('bgr24')
      File "/home/ischnell/ets/ETS_3.0.0b1/Enable_3.0.0b1/enthought/kiva/agg/tests/test_save.py", line 39, in do_check_format
        self.format_output_map[fmt])
    AssertionError: [255, 255, 255, 255, 255, 255, 255, 0, 0, 255, 0, 0]
                 != [255, 255, 255, 255, 255, 255, 0, 0, 255, 0, 0, 255]
    
    ======================================================================
    FAIL: test_bgra32_format (test_save.TestSave)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/ischnell/ets/ETS_3.0.0b1/Enable_3.0.0b1/enthought/kiva/agg/tests/test_save.py", line 27, in test_bgra32_format
        self.do_check_format('bgra32')
      File "/home/ischnell/ets/ETS_3.0.0b1/Enable_3.0.0b1/enthought/kiva/agg/tests/test_save.py", line 39, in do_check_format
        self.format_output_map[fmt])
    AssertionError: [255, 255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 255, 255, 0, 0, 255]
                 != [255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 255, 255, 0, 0, 255, 255]
    
    ----------------------------------------------------------------------
    Ran 4 tests in 0.014s
    
    FAILED (failures=2)

https://svn.enthought.com/enthought/ticket/1478

**Comment by itziakos** [comment]
@jwiggins, I think that this issue is not valid any more.

**Comment by jwiggins** [comment]
You're right. This an an ancient issue that was brought over in the move from SVN -> Git+Github
