### ISSUE TITLE
Test failure when both wxpython and pyside are installed

### ISSUE THREAD

**Issue by cournape** [enthought/enable#219]
This is what I see on Linux:

```
======================================================================
ERROR: Failure: ValueError (cannot set toolkit to wx because it has already been set to qt4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/.jaguar/envs/test-enable/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/vagrant/.jaguar/envs/test-enable/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vagrant/.jaguar/envs/test-enable/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/vagrant/.jaguar/envs/test-enable/lib/python2.7/site-packages/enable/savage/svg/tests/test_document.py", line 6, in <module>
    from enable.savage.svg.backends.kiva.renderer import Renderer as KivaRenderer
  File "/home/vagrant/.jaguar/envs/test-enable/lib/python2.7/site-packages/enable/savage/svg/backends/kiva/renderer.py", line 7, in <module>
    from enable.compiled_path import CompiledPath as KivaCompiledPath
  File "/home/vagrant/.jaguar/envs/test-enable/lib/python2.7/site-packages/enable/compiled_path.py", line 17, in <module>
    from toolkit import toolkit_object
  File "/home/vagrant/.jaguar/envs/test-enable/lib/python2.7/site-packages/enable/toolkit.py", line 47, in <module>
    _init_toolkit()
  File "/home/vagrant/.jaguar/envs/test-enable/lib/python2.7/site-packages/enable/toolkit.py", line 30, in _init_toolkit
    traits_toolkit()
  File "/home/vagrant/.jaguar/envs/test-enable/lib/python2.7/site-packages/traitsui/toolkit.py", line 125, in toolkit
    ETSConfig.toolkit = toolkit_name
  File "/home/vagrant/.jaguar/envs/test-enable/lib/python2.7/site-packages/traits/etsconfig/etsconfig.py", line 213, in _set_toolkit
    "already been set to %s" % (toolkit, self._toolkit)
ValueError: cannot set toolkit to wx because it has already been set to qt4
```

**Comment by jwiggins** [comment]
Is it possible that another part of ETS is hardcoding it to qt4? You should put a traceback printer in `ETSConfig._set_toolkit()` to find out who's calling. 

Alternatively, is it possible that your venv has `ETS_TOOLKIT` set to a specific value?

**Comment by rkern** [comment]
`nose`'s custom import logic may also be to blame.

**Comment by corranwebster** [comment]
Hopefully this should be fixed with Pyface & TraitsUI 5.1.0
