### ISSUE TITLE
Python setup.py installation fails

### ISSUE THREAD

**Issue by MichalKononenko** [enthought/enable#220]
I'm running a Fedora box, and trying to install this library in the process of installing [chaco](https://github.com/enthought/chaco). In installing it, I'm running into issues very similar to those of [#273](https://github.com/enthought/chaco/issues/273) on that repo. The board there suggests cloning the code and running ```python setup.py install``` in that repository. When I do this, my stack trace is

```
/usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:633: UserWarning: Specified path /usr/lib64/python2.7/site-packages/numpy/__init__.pyc/include/python2.7 is invalid.
  warnings.warn('Specified path %s is invalid.' % d)
/usr/lib64/python2.7/site-packages/numpy/distutils/system_info.py:633: UserWarning: Specified path /usr/local/include/python2.7 is invalid.
  warnings.warn('Specified path %s is invalid.' % d)
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    config = configuration().todict()
  File "setup.py", line 48, in configuration
    config.add_subpackage('kiva')
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
    caller_level = 2)
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
    caller_level = caller_level + 1)
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "kiva/setup.py", line 27, in configuration
    config.add_subpackage('agg')
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
    caller_level = 2)
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
    caller_level = caller_level + 1)
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "kiva/agg/setup.py", line 174, in configuration
    if int(m.group(1)) < 4:
AttributeError: 'NoneType' object has no attribute 'group'
```

My version of swig is 

```
swig.x86_64                            3.0.7-8.fc23             @updates  
```

Which I got by running

```bash
dnf list installed | grep swig
```

**Comment by jwiggins** [comment]
This is a regex match failure on the version string returned by `g++ --version`.

You must be running GCC 6.

MmmKludgyBuildScripts :tired_face:

**Comment by MichalKononenko** [comment]
Close. I'm running g++ 5.3.1. Here's what ```g++ --version``` returns

```
g++ (GCC) 5.3.1 20151207 (Red Hat 5.3.1-2)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

I got a temporary-ish solution by installing the dev version from this repository, and by hard-coding ```use_32bit_workaround``` to ```False```; kludging the kludgy script even more.

Thanks for your help

**Comment by olerichter** [comment]
same issue here

**Comment by jwiggins** [comment]
Seems odd that this would fail with g++ 5.3.1. I wasn't able to reproduce that locally.

Either way, #226 should address the problem.
