### ISSUE TITLE
Issue with rectangle markers under Python 3

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#235]
The following test code from Chaco works under Python 2, but fails under Python 3:

```
size = (50, 50)
scatterplot = create_scatter_plot(
    data=[range(10), range(10)],
    border_visible=False,
    marker_size=range(1, 11),
)
scatterplot.outer_bounds = list(size)
gc = PlotGraphicsContext(size)
gc.render_component(scatterplot)
```

the error generated seems to implicate the Python 3 swig bindings (from Travis CI run):

```
Traceback (most recent call last):
  File "/home/travis/build/enthought/chaco/build/lib.linux-x86_64-3.4/chaco/tests/scatterplot_renderers_test_case.py", line 71, in test_scatter_slow
    gc.render_component(scatterplot)
  File "/home/travis/build/enthought/chaco/build/lib.linux-x86_64-3.4/chaco/plot_graphics_context.py", line 58, in render_component
    component.draw(self, view_bounds=(0, 0, self.width(), self.height()))
  File "/home/travis/build/enthought/chaco/enable/build/lib.linux-x86_64-3.4/enable/component.py", line 424, in draw
    self._draw(gc, view_bounds, mode)
  File "/home/travis/build/enthought/chaco/enable/build/lib.linux-x86_64-3.4/enable/component.py", line 776, in _draw
    self._dispatch_draw(layer, gc, view_bounds, mode)
  File "/home/travis/build/enthought/chaco/enable/build/lib.linux-x86_64-3.4/enable/component.py", line 796, in _dispatch_draw
    handler(gc, view_bounds, mode)
  File "/home/travis/build/enthought/chaco/build/lib.linux-x86_64-3.4/chaco/base_xy_plot.py", line 466, in _draw_plot
    self._draw_component(gc, view_bounds, mode)
  File "/home/travis/build/enthought/chaco/build/lib.linux-x86_64-3.4/chaco/base_xy_plot.py", line 474, in _draw_component
    self._render(gc, pts)
  File "/home/travis/build/enthought/chaco/build/lib.linux-x86_64-3.4/chaco/scatterplot.py", line 482, in _render
    self.custom_symbol, point_mask=self._cached_point_mask)
  File "/home/travis/build/enthought/chaco/build/lib.linux-x86_64-3.4/chaco/scatterplot.py", line 141, in render_markers
    marker.add_to_path(gc, size)
  File "/home/travis/build/enthought/chaco/enable/build/lib.linux-x86_64-3.4/enable/markers.py", line 51, in add_to_path
    self._add_to_path(path, size)
  File "/home/travis/build/enthought/chaco/enable/build/lib.linux-x86_64-3.4/enable/markers.py", line 78, in _add_to_path
    path.rect(-size, -size, size * 2, size * 2)
  File "/home/travis/build/enthought/chaco/enable/build/lib.linux-x86_64-3.4/kiva/agg/agg.py", line 1026, in rect
    def rect(self, *args): return _agg.GraphicsContextArray_rect(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'GraphicsContextArray_rect'.
  Possible C/C++ prototypes are:
    kiva::graphics_context_base::rect(kiva::rect_type &)
    kiva::graphics_context_base::rect(double,double,double,double)
```

It should be possible to reduce this to a pure Enable issue.

**Comment by jwiggins** [comment]
Cannot reproduce.
