### ISSUE TITLE
Path resolution for _version.py in setup.py

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#254]
~~The setup.py file assumes it is being run from the same directory as it is in.  Pip doesn't always do this.~~  Gives this error (eg. running in an otherwise clean virtual environment):
```
Processing ./enable-4.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qp/t7g3hmrs7tb24jhkq6b3wn_00000gq/T/pip-c_hp5a-build/setup.py", line 225, in <module>
        write_version_py(filename='enable/_version.py')
      File "/private/var/folders/qp/t7g3hmrs7tb24jhkq6b3wn_00000gq/T/pip-c_hp5a-build/setup.py", line 103, in write_version_py
        raise ImportError("Unable to import git_revision. Try removing "
    ImportError: Unable to import git_revision. Try removing kiva/_version.py and the build directory before building.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qp/t7g3hmrs7tb24jhkq6b3wn_00000gq/T/pip-c_hp5a-build/
```

**Comment by corranwebster** [comment]
Actual problem was that six wasn't installed.  Needs to be a requirement.

**Comment by corranwebster** [comment]
But the import is somewhat more nefarious on Python 3 as it pulls in other code, including things which haven't yet been run through 2to3, and so fail:
```
Processing ./enable-4.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/folders/qp/t7g3hmrs7tb24jhkq6b3wn_00000gq/T/pip-ujuz3juz-build/setup.py", line 225, in <module>
        write_version_py(filename='enable/_version.py')
      File "/var/folders/qp/t7g3hmrs7tb24jhkq6b3wn_00000gq/T/pip-ujuz3juz-build/setup.py", line 101, in write_version_py
        from kiva._version import git_revision, full_version
      File "/private/var/folders/qp/t7g3hmrs7tb24jhkq6b3wn_00000gq/T/pip-ujuz3juz-build/kiva/__init__.py", line 21, in <module>
        from .fonttools import Font
      File "/private/var/folders/qp/t7g3hmrs7tb24jhkq6b3wn_00000gq/T/pip-ujuz3juz-build/kiva/fonttools/__init__.py", line 1, in <module>
        from .font import Font, str_to_font
      File "/private/var/folders/qp/t7g3hmrs7tb24jhkq6b3wn_00000gq/T/pip-ujuz3juz-build/kiva/fonttools/font.py", line 11, in <module>
        from .font_manager import FontProperties, fontManager
      File "/private/var/folders/qp/t7g3hmrs7tb24jhkq6b3wn_00000gq/T/pip-ujuz3juz-build/kiva/fonttools/font_manager.py", line 206
        except OSError, e:
                      ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/folders/qp/t7g3hmrs7tb24jhkq6b3wn_00000gq/T/pip-ujuz3juz-build/
```

It shouldn't be an import, instead it should compile and exec the _version.py
