### ISSUE TITLE
CompiledPath object has no attribute get_current_point

### ISSUE THREAD

**Issue by achabotl** [enthought/enable#267]
Executing the demo [chaco/examples/demo/status_overlay.py](https://github.com/enthought/chaco/blob/master/examples/demo/status_overlay.py) and clicking on the "Error" button raises an `AttributeError: 'CompiledPath' object has no attribute 'get_current_point'`.

- Enable version: 4.6.0
- Chaco version: 4.6.0
- Python 2.7.11 --  64-bit, on OS X.

```python
Exception occurred in traits notification handler for object: <__main__.MyPlot object at 0x11f18d170>, trait: error_button, old value: <undefined>, new value: 0
Traceback (most recent call last):
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "status_overlay.py", line 43, in _error_button_fired
    align='ul', scale_factor=0.25)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/chaco/layers/status_layer.py", line 59, in __init__
    self.document = SVGDocument(root, renderer=KivaRenderer)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enable/savage/svg/document.py", line 264, in __init__
    path, ops = self.processElement(element)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enable/savage/svg/document.py", line 379, in processElement
    path, ops = handler(element)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enable/savage/svg/document.py", line 478, in addGroupToDocument
    cpath, cops = self.processElement(child)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enable/savage/svg/document.py", line 379, in processElement
    path, ops = handler(element)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enable/savage/svg/document.py", line 478, in addGroupToDocument
    cpath, cops = self.processElement(child)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enable/savage/svg/document.py", line 379, in processElement
    path, ops = handler(element)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enable/savage/svg/document.py", line 478, in addGroupToDocument
    cpath, cops = self.processElement(child)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enable/savage/svg/document.py", line 379, in processElement
    path, ops = handler(element)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enable/savage/svg/document.py", line 133, in inner
    results = func(self, node, path)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enable/savage/svg/document.py", line 738, in addPathDataToDocument
    self.addPathDataToPath(node.get('d', ''), path)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enable/savage/svg/document.py", line 773, in addPathDataToPath
    self.addStrokeToPath(path, stroke)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enable/savage/svg/document.py", line 1071, in addStrokeToPath
    path.elliptical_arc_to(rx, ry, angle, large_arc_flag, sweep_flag, x2, y2)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enable/savage/svg/backends/kiva/renderer.py", line 47, in elliptical_arc_to
    x1, y1 = self.get_current_point()
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/kiva/agg/agg.py", line 685, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, CompiledPath, name)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/kiva/agg/agg.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'CompiledPath' object has no attribute 'get_current_point'
```

**Comment by jwiggins** [comment]
Huh... Sorry about that. It looks like that's a really old bug.

You can work around it using the following environment variable: `ETS_TOOLKIT=qt4.quartz` (or `qt4.qpainter`). The code appears to be expecting the quartz kiva backend and fails otherwise.

**Comment by achabotl** [comment]
Thanks John!
