### ISSUE TITLE
'Edit component properties' dialog gives traceback for any change

### ISSUE THREAD

**Issue by jwiggins** [enthought/enable#3]
In Converge, when you double-click a component in a data dependency graph, the 'Edit component properties' dialog box opens, but the following traceback occurs:
```
Traceback (most recent call last):
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\trait_notifiers.py", line 219, in rebind_call_1
    getattr( self.object(), self.name )( new )
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\wx\enable_rgba_color_editor.py", line 163, in update_object
    self.value = self._picker.color
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\editor.py", line 162, in _set_value
    self.ui.do_undoable( self.__set_value, value )
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\ui.py", line 518, in do_undoable
    action( _args, *_kw )
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\editor.py", line 172, in __set_value
    method( self.ui.info, self.object, self.name, value )
TypeError: setattr() takes exactly 4 arguments (5 given)
Exception occurred in traits notification handler
Traceback (most recent call last):
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\trait_notifiers.py", line 219, in rebind_call_1
    getattr( self.object(), self.name )( new )
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\wx\enable_rgba_color_editor.py", line 163, in update_object
    self.value = self._picker.color
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\editor.py", line 162, in _set_value
    self.ui.do_undoable( self.__set_value, value )
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\ui.py", line 518, in do_undoable
    action( _args, *_kw )
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\editor.py", line 172, in __set_value
    method( self.ui.info, self.object, self.name, value )
TypeError: setattr() takes exactly 4 arguments (5 given)
Exception occurred in traits notification handler
Traceback (most recent call last):
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\trait_notifiers.py", line 219, in rebind_call_1
    getattr( self.object(), self.name )( new )
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\wx\enable_rgba_color_editor.py", line 163, in update_object
    self.value = self._picker.color
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\editor.py", line 162, in _set_value
    self.ui.do_undoable( self.__set_value, value )
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\ui.py", line 518, in do_undoable
    action( _args, *_kw )
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\editor.py", line 172, in __set_value
    method( self.ui.info, self.object, self.name, value )
TypeError: setattr() takes exactly 4 arguments (5 given)
Exception occurred in traits notification handler
Traceback (most recent call last):
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\trait_notifiers.py", line 219, in rebind_call_1
    getattr( self.object(), self.name )( new )
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\wx\enable_rgba_color_editor.py", line 163, in update_object
    self.value = self._picker.color
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\editor.py", line 162, in _set_value
    self.ui.do_undoable( self.__set_value, value )
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\ui.py", line 518, in do_undoable
    action( _args, *_kw )
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\editor.py", line 172, in __set_value
    method( self.ui.info, self.object, self.name, value )
TypeError: setattr() takes exactly 4 arguments (5 given)
```

Changing any attribute in the dialog gives a traceback ending in the same TypeError. For example, changing the Padding Left value: 

```
Traceback (most recent call last):
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\wx\range_editor.py", line 312, in update_object_on_enter
    self.value = value = eval( self.control.text.GetValue().strip() )
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\editor.py", line 162, in _set_value
    self.ui.do_undoable( self.__set_value, value )
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\ui.py", line 518, in do_undoable
    action( _args, *_kw )
  File "c:\work\svn\enthought\trunk\src\lib\enthought\traits\ui\editor.py", line 172, in __set_value
    method( self.ui.info, self.object, self.name, value )
TypeError: setattr() takes exactly 4 arguments (5 given)
```

https://svn.enthought.com/enthought/ticket/634

**Comment by rahulporuri** [comment]
@jwiggins I don't fully understand this issue and I don't know if its worth keeping it open.

**Comment by jwiggins** [comment]
I'm happy to close since it's so old
