### ISSUE TITLE
enable-4.7.1: tests fail

### ISSUE THREAD

**Issue by pacho2** [enthought/enable#303]
We get this error:
https://bugs.gentoo.org/654090

======================================================================
ERROR: Failure: ValueError (Attempted relative import in non-package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib64/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib64/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/var/tmp/portage/dev-python/enable-4.7.1/work/enable-4.7.1-python2_7/build/lib/kiva/tests/test_cairo_drawing.py", line 5, in <module>
    import cairo  # noqa
  File "/var/tmp/portage/dev-python/enable-4.7.1/work/enable-4.7.1-python2_7/build/lib/kiva/cairo.py", line 18, in <module>
    from .arc_conversion import arc_to_tangent_points
ValueError: Attempted relative import in non-package

======================================================================
FAIL: enable.tests.test_assistant_test_case.test_mouse_move_real_window
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/enable-4.7.1/work/enable-4.7.1-python2_7/build/lib/enable/tests/test_assistant_test_case.py", line 29, in test_mouse_move_real_window
    window = Window(None, component=component)
  File "/var/tmp/portage/dev-python/enable-4.7.1/work/enable-4.7.1-python2_7/build/lib/enable/wx/base_window.py", line 172, in __init__
    self.control = control = self._create_control(parent, wid, pos, size)
  File "/var/tmp/portage/dev-python/enable-4.7.1/work/enable-4.7.1-python2_7/build/lib/enable/wx/base_window.py", line 221, in _create_control
    wx.WANTS_CHARS)
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 9145, in __init__
    _core_.Window_swiginit(self,_core_.new_Window(*args, **kwargs))
PyAssertionError: C++ assertion "Assert failure" failed at /var/tmp/portage/x11-libs/wxGTK-3.0.3/work/wxWidgets-3.0.3/src/gtk/window.cpp(2430) in Create(): wxWindowGTK creation failed

======================================================================
FAIL: enable.tests.test_assistant_test_case.test_mouse_move_real_window_mocked_position
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/enable-4.7.1/work/enable-4.7.1-python2_7/build/lib/enable/tests/test_assistant_test_case.py", line 51, in test_mouse_move_real_window_mocked_position
    window = Window(None, component=component)
  File "/var/tmp/portage/dev-python/enable-4.7.1/work/enable-4.7.1-python2_7/build/lib/enable/wx/base_window.py", line 172, in __init__
    self.control = control = self._create_control(parent, wid, pos, size)
  File "/var/tmp/portage/dev-python/enable-4.7.1/work/enable-4.7.1-python2_7/build/lib/enable/wx/base_window.py", line 221, in _create_control
    wx.WANTS_CHARS)
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 9145, in __init__
    _core_.Window_swiginit(self,_core_.new_Window(*args, **kwargs))
PyAssertionError: C++ assertion "Assert failure" failed at /var/tmp/portage/x11-libs/wxGTK-3.0.3/work/wxWidgets-3.0.3/src/gtk/window.cpp(2430) in Create(): wxWindowGTK creation failed

----------------------------------------------------------------------
Ran 538 tests in 56.483s

FAILED (SKIP=30, errors=1, failures=2)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
PyAssertionError: C++ assertion "GetEventHandler() == this" failed at /var/tmp/portage/x11-libs/wxGTK-3.0.3/work/wxWidgets-3.0.3/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
wx._core.PyAssertionError: C++ assertion "GetEventHandler() == this" failed at /var/tmp/portage/x11-libs/wxGTK-3.0.3/work/wxWidgets-3.0.3/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

Thanks for your help

**Comment by jwiggins** [comment]
Hi @pacho2! Thanks for the report.

Something I noticed when looking through the logs on the Gentoo bug report was that the build script is running `nosetests --verbose` to run tests on enable and kiva. I would recommend against this. Instead, you might get better results if you run the tests in the same way that we do.

(From https://github.com/enthought/enable/blob/master/ci/edmtool.py#L175-L176):
```
coverage run -m nose.core enable -v
coverage run -a -m nose.core kiva -v
```

`nosetests` does some pretty strange things to the import environment. You can see this in your traceback where `import cairo` should be importing the top-level `cairo` package, but instead finds the `kiva.cairo` module in our library (followed by a failure that shouldn't happen).

As for the Wx-related errors, I can't really speak to those right now. We're working on updating Wx code in other parts of ETS, so it's possible there are some fixes there that we need to make.

**Comment by pacho2** [comment]
Hi, running tests in that way I get the wx errors, but I guess we will need to wait for that fixes to be included :)
[enable-4.7.1:20180527-133313.log.gz](https://github.com/enthought/enable/files/2042668/enable-4.7.1.20180527-133313.log.gz)
