### ISSUE TITLE
TypeError when calling linear_gradient

### ISSUE THREAD

**Issue by rahulporuri** [enthought/enable#342]
The `CtfEditor` in `ensemble` uses `GraphicsContext.linear_gradient`. The PR https://github.com/enthought/ensemble/pull/65 adds a `from __future__ import unicode_literals` import to the top of the module, which leads to a `TypeError` in the test output on CI.

The traceback is 
```
test_mouse_drag_alpha (ensemble.ctf.tests.test_editor.TestEditor) ... Traceback (most recent call last):
  File "/home/travis/.edm/envs/ensemble-test-2.7-pyside/lib/python2.7/site-packages/enable/qt4/base_window.py", line 202, in paintEvent
    self.handler.paintEvent(event)
  File "/home/travis/.edm/envs/ensemble-test-2.7-pyside/lib/python2.7/site-packages/enable/qt4/base_window.py", line 54, in paintEvent
    self._enable_window._paint(event)
  File "/home/travis/.edm/envs/ensemble-test-2.7-pyside/lib/python2.7/site-packages/enable/abstract_window.py", line 468, in _paint
    self.component.draw(gc, view_bounds=(0, 0, size[0], size[1]))
  File "/home/travis/.edm/envs/ensemble-test-2.7-pyside/lib/python2.7/site-packages/enable/component.py", line 427, in draw
    self._draw(gc, view_bounds, mode)
  File "/home/travis/.edm/envs/ensemble-test-2.7-pyside/lib/python2.7/site-packages/enable/component.py", line 779, in _draw
    self._dispatch_draw(layer, gc, view_bounds, mode)
  File "/home/travis/.edm/envs/ensemble-test-2.7-pyside/lib/python2.7/site-packages/enable/container.py", line 257, in _dispatch_draw
    my_handler(gc, view_bounds, mode)
  File "/home/travis/build/enthought/ensemble/ensemble/ctf/editor.py", line 183, in _draw_container_mainlayer
    self._draw_colors(color_nodes, gc)
  File "/home/travis/build/enthought/ensemble/ensemble/ctf/editor.py", line 209, in _draw_colors
    gc.linear_gradient(0, 0, w, 0, grad_stops, 'pad', 'userSpaceOnUse')
  File "/home/travis/.edm/envs/ensemble-test-2.7-pyside/lib/python2.7/site-packages/kiva/agg/agg.py", line 1500, in linear_gradient
    return _agg.GraphicsContextArray_linear_gradient(self, *args)
TypeError: in method 'GraphicsContextArray_linear_gradient', argument 7 of type 'char const *'
ok
```

Note that the tests themselves passed. This traceback wasn't seen earlier when the `unicode_literals` import wasn't present.

**Comment by jwiggins** [comment]
I think a SWIG typemap might be needed to convert `unicode` to `const char*`
