### ISSUE TITLE
Test failures on Windows / Python 2.7 / wx

### ISSUE THREAD

**Issue by mdickinson** [enthought/enable#355]
Some [Appveyor builds](https://ci.appveyor.com/project/EnthoughtOSS/enable/builds/25249012/job/adjcs1o7uiu0fi5v) are showing failures on Windows / Python 2.7. I haven't looked deeper to see which of these failures (if any) are intermittent and which are reliable.

Note that Appveyor is currently only set up to run on pushes, not on pull requests. We probably want to fix that, but then CI will fail until we get this issue sorted out.

Here's the tail of the output on one such build:
```
======================================================================
FAIL: test_horizontal_mouse_wheel (enable.tests.wx.mouse_wheel_test_case.MouseWheelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\enable-4.7.1.dev87-py2.7-win-amd64.egg\enable\tests\wx\mouse_wheel_test_case.py", line 85, in test_horizontal_mouse_wheel
    self.assertEqual(self.tool.event.mouse_wheel_delta, (200, 0))
AssertionError: <undefined> != (200, 0)
======================================================================
FAIL: test_vertical_mouse_wheel (enable.tests.wx.mouse_wheel_test_case.MouseWheelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\enable-4.7.1.dev87-py2.7-win-amd64.egg\enable\tests\wx\mouse_wheel_test_case.py", line 66, in test_vertical_mouse_wheel
    self.assertEqual(self.tool.event.mouse_wheel_delta, (0, 200))
AssertionError: <undefined> != (0, 200)
======================================================================
FAIL: enable.tests.test_assistant_test_case.test_mouse_move_real_window
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\traitsui\tests\_tools.py", line 129, in wrapper
    return test_func(*args, **kwargs)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\enable-4.7.1.dev87-py2.7-win-amd64.egg\enable\tests\test_assistant_test_case.py", line 32, in test_mouse_move_real_window
    window = Window(None, component=component)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\enable-4.7.1.dev87-py2.7-win-amd64.egg\enable\wx\base_window.py", line 172, in __init__
    self.control = control = self._create_control(parent, wid, pos, size)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\enable-4.7.1.dev87-py2.7-win-amd64.egg\enable\wx\base_window.py", line 221, in _create_control
    wx.WANTS_CHARS)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\wx\_core.py", line 9145, in __init__
    _core_.Window_swiginit(self,_core_.new_Window(*args, **kwargs))
PyAssertionError: C++ assertion "parent" failed at ..\..\src\msw\window.cpp(522) in wxWindow::Create(): can't create wxWindow without parent
======================================================================
FAIL: enable.tests.test_assistant_test_case.test_mouse_move_real_window_mocked_position
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\traitsui\tests\_tools.py", line 129, in wrapper
    return test_func(*args, **kwargs)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\enable-4.7.1.dev87-py2.7-win-amd64.egg\enable\tests\test_assistant_test_case.py", line 54, in test_mouse_move_real_window_mocked_position
    window = Window(None, component=component)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\enable-4.7.1.dev87-py2.7-win-amd64.egg\enable\wx\base_window.py", line 172, in __init__
    self.control = control = self._create_control(parent, wid, pos, size)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\enable-4.7.1.dev87-py2.7-win-amd64.egg\enable\wx\base_window.py", line 221, in _create_control
    wx.WANTS_CHARS)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\wx\_core.py", line 9145, in __init__
    _core_.Window_swiginit(self,_core_.new_Window(*args, **kwargs))
PyAssertionError: C++ assertion "parent" failed at ..\..\src\msw\window.cpp(522) in wxWindow::Create(): can't create wxWindow without parent
======================================================================
FAIL: enable.tests.test_component_editor.test_initial_component_with_item_size
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\traitsui\tests\_tools.py", line 129, in wrapper
    return test_func(*args, **kwargs)
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\site-packages\enable-4.7.1.dev87-py2.7-win-amd64.egg\enable\tests\test_component_editor.py", line 64, in test_initial_component_with_item_size
    nose.tools.assert_less(size[1], ITEM_HEIGHT+30)
AssertionError: 241 not less than 230
----------------------------------------------------------------------
Ran 257 tests in 2.203s
FAILED (SKIP=7, failures=5)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
PyAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\enable-test-2.7-wx-pillow\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
wx._core.PyAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed
```

**Comment by rahulporuri** [comment]
Ahh. These are expected errors that travis ignores but appveyor doesnt. fix coming.

**Comment by aaronayres35** [comment]
@rahulporuri can I close this since we no longer test against python 2.7?

**Comment by rahulporuri** [comment]
thanks for triaging the issue. we can close this issue as it is outdated.

**Comment by aaronayres35** [comment]
closing based on above
