### ISSUE TITLE
GraphicsContextArray missing its __swig_setmethods__ attribute?

### ISSUE THREAD

**Issue by capn-freako** [enthought/enable#359]
After porting one of my *Traits/UI/Chaco/Enable* projects from Python2 to Python3, I'm getting the following error, which I'm having a hard time troubleshooting.
I was hoping someone might have a suggestion for making forward progress.

Thanks!  
-db  
:)

```
Traceback (most recent call last):
  File "/anaconda3/envs/pybert64/lib/python3.7/site-packages/enable/qt4/base_window.py", line 213, in paintEvent
    self.handler.paintEvent(event)
  File "/anaconda3/envs/pybert64/lib/python3.7/site-packages/enable/qt4/base_window.py", line 65, in paintEvent
    self._enable_window._paint(event)
  File "/anaconda3/envs/pybert64/lib/python3.7/site-packages/enable/abstract_window.py", line 462, in _paint
    self._gc = self._create_gc(size)
  File "/anaconda3/envs/pybert64/lib/python3.7/site-packages/enable/qt4/image.py", line 23, in _create_gc
    bottom_up = 0)
  File "/anaconda3/envs/pybert64/lib/python3.7/site-packages/kiva/agg/__init__.py", line 40, in __init__
    bottom_up)
  File "/anaconda3/envs/pybert64/lib/python3.7/site-packages/kiva/agg/agg.py", line 888, in __init__
    _swig_setattr(self, GraphicsContextArray, 'this', obj)
  File "/anaconda3/envs/pybert64/lib/python3.7/site-packages/kiva/agg/agg.py", line 39, in _swig_setattr
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)
  File "/anaconda3/envs/pybert64/lib/python3.7/site-packages/kiva/agg/agg.py", line 29, in _swig_setattr_nondynamic
    method = class_type.__swig_setmethods__.get(name, None)
AttributeError: type object 'GraphicsContextArray' has no attribute '__swig_setmethods__'
```

My package versions:

```
dbanas@davids-mbp:~/Documents/Projects/PyBERT
$ conda list | grep 'traitsui\|traits\|chaco\|enable\|swig'
chaco                     4.8.0                    py37_0    local
enable                    4.8.0              pyh7b7c402_0    local
swig                      3.0.12               h1cb45b9_3
traits                    5.1.1            py37h1de35cc_0
traitsui                  6.1.1                      py_0
```

**Comment by jwiggins** [comment]
If you look at `/anaconda3/envs/pybert64/lib/python3.7/site-packages/kiva/agg/agg.py` can you see the `GraphicsContextArray` class and its contents? It should have `__swig_setmethods__`.

This is code which is generated by SWIG when building enable. I suspect that there was a problem when the package was built, but I can't confirm with the provided information.

**Comment by capn-freako** [comment]
Hi John,

Thanks for your reply!

Yes, I do see the GraphicsContextArray class definition in the file you mention:

class GraphicsContextArray(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

And, no, it has no __swig_setmethods__ attribute.

-db

**Comment by jwiggins** [comment]
That's fairly suspicious looking. Here's what a built version should look like:
```
class GraphicsContextArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GraphicsContextArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GraphicsContextArray, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

                # We define our own constructor AND destructor.
    def __init__(self, ary_or_size, pix_format="bgra32",
                 interpolation="nearest", bottom_up=1):
```
So: How are you building enable and are you seeing errors during this process that aren't fatal but probably should be (given the result)?

**Comment by capn-freako** [comment]
I've downloaded the "4.8.0" release of the _enable_ source code from its Git repository.
And I'm using the following command to build: `conda build --numpy 1.16 conda.recipe/enable/`.

Contents of `conda.recipe/enable/`:

```
$ ls conda.recipe/enable/
meta.yaml   meta.yaml~
```

Excerpted content of `meta.yaml`:

```yaml
{% set name = "enable" %}
{% set version = "4.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../../enable/

build:
  number: 0
  noarch: "python"
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - fonttools
    - numpy
    - pillow
    - pip
    - pyface
    - python
    - six
    - traits
    - traitsui
    - Cython
  run:
    - fonttools
    - numpy
    - pillow
    - pyface
    - pyparsing
    - python
    - six
    - traits
    - traitsui

test:
  imports:
    - enable
    - enable.drawing
{snip}
```

Some bits of the build output that look suspicious to me:

```
Solving environment: ...working... done
    Running command python setup.py egg_info
    fatal: not a git repository: /private/tmp/pip-req-build-on3lsg0o/../.git/modules/enable
    fatal: not a git repository: /private/tmp/pip-req-build-on3lsg0o/../.git/modules/enable
    non-existing path in 'kiva/agg': '/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Headers'
    non-existing path in 'kiva/agg': '/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers'
    non-existing path in 'kiva/agg': '/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Headers'
    non-existing path in 'kiva/agg': '/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers'
    non-existing path in 'kiva/quartz': '/System/Library/Frameworks/Cocoa.framework/Versions/A/Headers'
    non-existing path in 'kiva/quartz': '/System/Library/Frameworks/CoreFoundation.framework/Versions/A/Headers'
    non-existing path in 'kiva/quartz': '/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Headers'
    non-existing path in 'kiva/quartz': '/System/Library/Frameworks/Foundation.framework/Versions/A/Headers'
    Could not locate executable wx-config
    File not found: None. Cannot determine wx info.
    /bin/sh: hg: command not found
```

```
  running build_py
  copying kiva/_version.py -> build/lib.macosx-10.7-x86_64-3.7/kiva
  copying build/src.macosx-10.7-x86_64-3.7/kiva/agg/agg.py -> build/lib.macosx-10.7-x86_64-3.7/kiva/agg
  copying build/src.macosx-10.7-x86_64-3.7/kiva/agg/src/gl/plat_support.py -> build/lib.macosx-10.7-x86_64-3.7/kiva/agg
  copying enable/_version.py -> build/lib.macosx-10.7-x86_64-3.7/enable
  warning: MyBuildPy: byte-compiling is disabled, skipping.
```

Lot's of deprecation warnings similar to:

```
  kiva/agg/freetype2/src/base/ftmac.c:279:19: warning: 'FSPathMakeRef' is deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
      if ( noErr != FSPathMakeRef( pathname, &ref, FALSE ) )
```

```
  g++ -bundle -undefined dynamic_lookup -L/anaconda3/conda-bld/enable_1562695607866/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -arch x86_64 -L/anaconda3/conda-bld/enable_1562695607866/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/build/src.macosx-10.7-x86_64-3.7/kiva/agg/agg_wrap.o -Lbuild/temp.macosx-10.7-x86_64-3.7 -lkiva_src -lagg24_src -lfreetype2_src -o build/lib.macosx-10.7-x86_64-3.7/kiva/agg/_agg.cpython-37m-darwin.so -framework ApplicationServices -framework OpenGL
  ld: warning: object file (build/temp.macosx-10.7-x86_64-3.7/libkiva_src.a(kiva_compiled_path.o)) was built for newer OSX version (10.14) than being linked (10.9)
  ld: warning: object file (build/temp.macosx-10.7-x86_64-3.7/libkiva_src.a(kiva_rect.o)) was built for newer OSX version (10.14) than being linked (10.9)
  ld: warning: object file (build/temp.macosx-10.7-x86_64-3.7/libkiva_src.a(kiva_affine_helpers.o)) was built for newer OSX version (10.14) than being linked (10.9)
  ld: warning: object file (build/temp.macosx-10.7-x86_64-3.7/libkiva_src.a(kiva_graphics_context_base.o)) was built for newer OSX version (10.14) than being linked (10.9)
  ld: warning: object file (build/temp.macosx-10.7-x86_64-3.7/libkiva_src.a(gl_graphics_context.o)) was built for newer OSX version (10.14) than being linked (10.9)
  ld: warning: object file (build/temp.macosx-10.7-x86_64-3.7/libkiva_src.a(kiva_gradient.o)) was built for newer OSX version (10.14) than being linked (10.9)
  ld: warning: object file (build/temp.macosx-10.7-x86_64-3.7/libkiva_src.a(kiva_font_type.o)) was built for newer OSX version (10.14) than being linked (10.9)
```

```
  copying build/lib.macosx-10.7-x86_64-3.7/kiva/celiagg.py -> build/bdist.macosx-10.7-x86_64/wheel/kiva
  copying build/lib.macosx-10.7-x86_64-3.7/kiva/image.py -> build/bdist.macosx-10.7-x86_64/wheel/kiva
  warning: install_lib: byte-compiling is disabled, skipping.
```

```
Fixing linking of /usr/lib/libSystem.B.dylib in /anaconda3/conda-bld/enable_1562695607866/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.7/site-packages/kiva/agg/_plat_support.cpython-37m-darwin.so
New link location is None
WARNING (enable,lib/python3.7/site-packages/kiva/_cython_speedups.cpython-37m-darwin.so): Needed DSO lib/libc++.1.dylib found in ['libcxx']
WARNING (enable,lib/python3.7/site-packages/kiva/_cython_speedups.cpython-37m-darwin.so): .. but ['libcxx'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
```

**Comment by jwiggins** [comment]
None of that looks particularly suspicious, other than the conda recipe omitting SWIG (which you have in the environment anyhow...). I'm not sure... Something about the creation of agg.py file is failing.

What happens if you use `pip` to install it?

**Comment by capn-freako** [comment]
```
(pybert64)
dbanas@davids-mbp:~/Documents/Projects/PyBERT
$ pip install ./enable/
Processing ./enable
Requirement already satisfied: numpy in /anaconda3/envs/pybert64/lib/python3.7/site-packages (from enable==4.8.0) (1.16.4)
Requirement already satisfied: traits in /anaconda3/envs/pybert64/lib/python3.7/site-packages (from enable==4.8.0) (5.1.1)
Requirement already satisfied: traitsui in /anaconda3/envs/pybert64/lib/python3.7/site-packages (from enable==4.8.0) (6.1.1)
Requirement already satisfied: pyface in /anaconda3/envs/pybert64/lib/python3.7/site-packages (from enable==4.8.0) (6.1.1)
Requirement already satisfied: six in /anaconda3/envs/pybert64/lib/python3.7/site-packages (from enable==4.8.0) (1.12.0)
Requirement already satisfied: fonttools in /anaconda3/envs/pybert64/lib/python3.7/site-packages (from enable==4.8.0) (3.43.1)
Building wheels for collected packages: enable
  Building wheel for enable (setup.py) ... done
  Stored in directory: /private/var/folders/43/ys_4mp490r348rgc9xrwzn400000gn/T/pip-ephem-wheel-cache-kibjki4k/wheels/03/80/24/30b1ee534350b345bd11f39f2e7a2257405034aeea55310028
Successfully built enable
ERROR: pybert 3.0.0 requires pyside2, which is not installed.
Installing collected packages: enable
  Found existing installation: enable 4.8.0
    Uninstalling enable-4.8.0:
      Successfully uninstalled enable-4.8.0
Successfully installed enable-4.8.0
```

Still no `__swig_setmethods__` attribute in the `GraphicsContextArray` class definition.

**Comment by jwiggins** [comment]
This line:
```
ERROR: pybert 3.0.0 requires pyside2, which is not installed.
```
... does not lead me to the question you answered. I'm more concerned why building enable would cause this message to be printed. Are you really building an unmodified version of enable? What sort of environment are you building it in? Is it really just a plain old conda environment with your application's dependencies installed in it?

To test this myself, I created a fresh conda environment with cython, numpy, swig, traits, and traitsui installed. Then I installed enable using pip (after `git clean -fxd`, just to be sure):
```
# packages in environment at ~/miniconda3/envs/enable-test:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py37_0  
cython                    0.29.11          py37h0a44026_0  
enable                    4.8.1.dev2               pypi_0    pypi
fonttools                 3.43.1                   pypi_0    pypi
intel-openmp              2019.4                      233  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
mkl                       2019.4                      233  
mkl_fft                   1.0.12           py37h5e564d8_0  
mkl_random                1.0.2            py37h27c97d8_0  
ncurses                   6.1                  h0a44026_1  
numpy                     1.16.4           py37hacdab7b_0  
numpy-base                1.16.4           py37h6575580_0  
openssl                   1.1.1c               h1de35cc_1  
pcre                      8.43                 h0a44026_0  
pillow                    6.1.0                    pypi_0    pypi
pip                       19.1.1                   py37_0  
pyface                    6.0.0                    py37_0  
pygments                  2.4.2                      py_0  
python                    3.7.3                h359304d_0  
readline                  7.0                  h1de35cc_5  
setuptools                41.0.1                   py37_0  
six                       1.12.0                   pypi_0    pypi
sqlite                    3.28.0               ha441bb4_0  
swig                      3.0.12               h1cb45b9_3  
tk                        8.6.8                ha441bb4_0  
traits                    5.1.1            py37h1de35cc_0  
traitsui                  6.1.1                      py_0  
wheel                     0.33.4                   py37_0  
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               h1de35cc_3  
```
Then when I inspect the file `~/miniconda3/envs/enable-test/lib/python3.7/site-packages/kiva/agg/agg.py`, I see a `GraphicsContextArray` with the expected SWIG machinery inside.

This leads me to believe that something is different about your conda environment and it's causing SWIG to get things wrong. I'm not particularly experienced with SWIG, so I won't speculate about what that could be.

**Comment by capn-freako** [comment]
1. Are you really building an unmodified version of enable?

    Yes:
	```
	(pybert64)
	dbanas@davids-mbp:~/Documents/Projects/PyBERT/enable
	$ git status
	HEAD detached at 4.8.0
	nothing to commit, working tree clean
	You have new mail in /var/mail/dbanas
	(pybert64)
	dbanas@davids-mbp:~/Documents/Projects/PyBERT/enable
	$ git diff
	(pybert64)
	dbanas@davids-mbp:~/Documents/Projects/PyBERT/enable
    $
	```
	
    However, whereas I'm building version "4.8.0" (because it's the most recent release), you appear to be building version "4.8.1.dev2".
	Maybe, I should try building that version?
	
1. What sort of environment are you building it in? Is it really just a plain old conda environment with your application's dependencies installed in it?

    I think so. Are there some commands I could run, in order to prove/disprove this?

**Comment by capn-freako** [comment]
I've been using a `conda build ...` command, from within the parent directory of `enable/`.
I just tried, instead, moving into the `enable/` directory and executing `python setup.py --help`:

```
(pybert64)
dbanas@davids-mbp:~/Documents/Projects/PyBERT/enable
$ python setup.py --help
/anaconda3/envs/pybert64/lib/python3.7/site-packages/numpy/distutils/system_info.py:731: UserWarning: Specified path /usr/local/include/python3.7m is invalid.
  return self.get_paths(self.section, key)
non-existing path in 'kiva/agg': '/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Headers'
non-existing path in 'kiva/agg': '/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers'
non-existing path in 'kiva/agg': '/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Headers'
non-existing path in 'kiva/agg': '/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers'
non-existing path in 'kiva/quartz': '/System/Library/Frameworks/Cocoa.framework/Versions/A/Headers'
non-existing path in 'kiva/quartz': '/System/Library/Frameworks/CoreFoundation.framework/Versions/A/Headers'
non-existing path in 'kiva/quartz': '/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Headers'
non-existing path in 'kiva/quartz': '/System/Library/Frameworks/Foundation.framework/Versions/A/Headers'
Could not locate executable wx-config
File not found: None. Cannot determine wx info.
/bin/sh: hg: command not found
```

Do you happen to know whether any of these reported omissions are critical?

**Comment by jwiggins** [comment]
1. I'm not _really_ building a different version of enable. It's effectively the same as yours:
```
[jwiggins: enable] (master)
$ git log --all --decorate --oneline --graph 
*   a843b37 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #351 from enthought/rel/4.8.0
|\  
| * a8281c1 Bump version to 4.8.1
| * d6ebe4f (tag: 4.8.0) Release 4.8.0
|/  
* bf539a8 Fix paths to static files. (#358)
```

2. My conda knowledge is pretty limited, so I wouldn't know what to suggest. Perhaps you can answer the question of what code prints this error?
```
ERROR: pybert 3.0.0 requires pyside2, which is not installed.
```

3. Those messages look bad, but they can safely be ignored. I see the same messages in my test conda environment.

--------

I'm basically at a loss here. However, we can try to isolate the problem. From within your conda environment, you can do the following:
```
$ cd enable/kiva/agg
$ swig -c++ -python -Isrc -Iagg-24/include agg.i
```
Were there any errors or warnings? Open the `agg.py` file which was generated in that directory and check its definition of the `GraphicsContextArray` class. Is it still missing the `__swig_setmethods__` dictionary?

**Comment by capn-freako** [comment]
Hi John,

Thanks for your continued invested time on this!

Re: your suggestion:

```
(PyBERT)
dbanas@Davids-MacBook-Pro:~/Documents/Projects/PyBERT/enable/kiva/agg
$ swig -c++ -python -Isrc -Iagg-24/include agg.i
(PyBERT)
dbanas@Davids-MacBook-Pro:~/Documents/Projects/PyBERT/enable/kiva/agg
$
```

No errors were generated, but I don't see a `__swig_setmethods__` attribute in the `GraphicsContextArray` class definition either. :(

**Comment by jwiggins** [comment]
OK. It seems like SWIG is the problem. Can you run the following so we can compare:
```
$ miniconda3/bin/conda run -n enable-test swig -version

SWIG Version 3.0.12

Compiled with x86_64-apple-darwin13.4.0-clang++ [x86_64-apple-darwin13.4.0]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
$ miniconda3/bin/conda run -n enable-test swig -swiglib
~/miniconda3/envs/enable-test/share/swig/3.0.12
$ echo $SWIG_FEATURES

```

**Comment by capn-freako** [comment]
```
(PyBERT)
dbanas@Davids-MacBook-Pro:~/Documents/Projects/PyBERT/enable/kiva/agg
$ swig -version

SWIG Version 4.0.0

Compiled with clang++ [x86_64-apple-darwin18.5.0]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
(PyBERT)
dbanas@Davids-MacBook-Pro:~/Documents/Projects/PyBERT/enable/kiva/agg
$ swig -swiglib
/usr/local/Cellar/swig/4.0.0/share/swig/4.0.0
```

**Comment by jwiggins** [comment]
Aha! I see some differences!

1. You're running SWIG 4.0.0 instead of 3.0.12
2. Your SWIG is coming from homebrew, not conda

So, the fastest way to fix this would be to uninstall the SWIG in homebrew: `$ brew uninstall swig`. Then you can try to run SWIG again in isolation to check if `agg.py` contains what it needs. You might also try `$ which swig` to ensure that you're using the binary your expect.

Alternatively, you can look at your $PATH to see why homebrew's bin directory is getting picked up ahead of the bin directory in your conda environments. That defeats the whole purpose of isolated environments.

**Comment by capn-freako** [comment]
Sorry, I should've mentioned that I've ripped Anaconda out of my system, in order to eliminate one possible source of trouble.

But, you were right: it was the SWIG version that was causing the problem:

```
(PyBERT)
dbanas@Davids-MacBook-Pro:~/Documents/Projects/PyBERT/enable/kiva/agg
$ brew install swig@3
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
{snip}
==> Downloading https://homebrew.bintray.com/bottles/swig@3-3.0.12.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/28/28e5c0a5e8aac0c0d5f58e4dd69c590f57d3a450d92aa35b18aee037ab7d8b60?__gda__=exp=1562869136~hmac=a6386afe80e84903fd535441af37934
######################################################################## 100.0%
==> Pouring swig@3-3.0.12.mojave.bottle.tar.gz
==> Caveats
swig@3 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have swig@3 first in your PATH run:
  echo 'export PATH="/usr/local/opt/swig@3/bin:$PATH"' >> ~/.bash_profile

==> Summary
🍺  /usr/local/Cellar/swig@3/3.0.12: 755 files, 5.4MB

(PyBERT)
dbanas@Davids-MacBook-Pro:~/Documents/Projects/PyBERT/enable/kiva/agg
$ /usr/local/opt/swig@3/bin/swig -version

SWIG Version 3.0.12

Compiled with clang++ [x86_64-apple-darwin18.6.0]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
(PyBERT)
dbanas@Davids-MacBook-Pro:~/Documents/Projects/PyBERT/enable/kiva/agg
$ /usr/local/opt/swig@3/bin/swig -swiglib
/usr/local/Cellar/swig@3/3.0.12/share/swig/3.0.12
(PyBERT)
dbanas@Davids-MacBook-Pro:~/Documents/Projects/PyBERT/enable/kiva/agg
$ /usr/local/opt/swig@3/bin/swig -c++ -python -Isrc -Iagg-24/include agg.i
(PyBERT)
dbanas@Davids-MacBook-Pro:~/Documents/Projects/PyBERT/enable/kiva/agg
$ less agg.py
```

And, I see:

```python
class GraphicsContextArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GraphicsContextArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GraphicsContextArray, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
```

Thank you for your help!

Now, is this a SWIG problem that I should report, or a matter of needing to bring *Enable* up-to-date w/ v4 of SWIG?

**Comment by jwiggins** [comment]
> I should've mentioned that I've ripped Anaconda out of my system, in order to eliminate one possible source of trouble.

I hope that's only temporary. [EDM](https://www.enthought.com/product/enthought-deployment-manager/) and conda are solid solutions for deploying Python applications of sufficient complexity.

>Now, is this a SWIG problem that I should report, or a matter of needing to bring Enable up-to-date w/ v4 of SWIG?

Good question. Don't know the answer, but I'll make an issue for when this inevitably comes up in the future. Thanks for working through this with me!

**Comment by lateralguy** [comment]
I was facing a similar issue after rolling back the packages to the following version:
enable = 4.8.0
swig = 3.0.12
The issue was resolved.
