### ISSUE TITLE
Update CI for Qt5

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#382]
Currently we are installing PyQt5 with pip rather than EDM - it is now available in EDM.

Additionally, we are not testing on PySide2; that _should_ be installed with pip as it isn't available on EDM at this time.

See the `etstool.py` script for TraitsUI or Pyface for an example.

**Comment by danieljfarrell** [comment]
I've trying to understand this because I'm making a new virtual environment for a python application. Would you expected enable to work with PyQt5 or shall I use PyQt4?

I'm getting the following error from enable when using a Chaco plot in a TraitsUI application

```
   from enable.api import ComponentEditor
  File "C:\Users\daniel.farrell\AppData\Local\Continuum\anaconda3\envs\teracota_aether5\envs\teracota_aether6\lib\site-packages\enable\api.py", line 21, in <module>
    from .markers import MarkerTrait, marker_trait, MarkerNameDict, marker_names, \
  File "C:\Users\daniel.farrell\AppData\Local\Continuum\anaconda3\envs\teracota_aether5\envs\teracota_aether6\lib\site-packages\enable\markers.py", line 18, in <module>
    from .compiled_path import CompiledPath
  File "C:\Users\daniel.farrell\AppData\Local\Continuum\anaconda3\envs\teracota_aether5\envs\teracota_aether6\lib\site-packages\enable\compiled_path.py", line 17, in <module>
    from .toolkit import toolkit_object
  File "C:\Users\daniel.farrell\AppData\Local\Continuum\anaconda3\envs\teracota_aether5\envs\teracota_aether6\lib\site-packages\enable\toolkit.py", line 47, in <module>
    _init_toolkit()
  File "C:\Users\daniel.farrell\AppData\Local\Continuum\anaconda3\envs\teracota_aether5\envs\teracota_aether6\lib\site-packages\enable\toolkit.py", line 40, in _init_toolkit
    format_exception_only(t, v)))
ImportError: Unable to import the image backend for the qt toolkit (reason: ["ModuleNotFoundError: No module named 'enable.qt'\n"]).
```

**Comment by corranwebster** [comment]
It should work with PyQt5, and probably should with PySide2 as well, but I don't think we have CI running on that).  However you will likely need to set the ETS_TOOLKIT (or ETSConfig.toolkit) to 'qt4' rather than just 'qt' even when using Qt5 (ETS_TOOLKIT=qt works for TraitsUI, but I don't think Enable has been updated).

In an environment with just PyQt5 it _should_ auto-detect; if it doesn't that's a bug.

**Comment by danieljfarrell** [comment]
OK, thanks! I’m have problems creating an environment with: traits, traitsui, chaco, enable, pyface and PyQt5. So this should work, that’s good to know. Ideally I would like to use Python 3.8 but I would use an older version if it makes it easier. I will try again again tomorrow, been trying for a few hours today with different conda and pip environment without success. You can imagine `conda create -n tcenv python=3.8` and the installing the packages `conda install traitsui pyqt` etc... everything works until the import error above. Maybe I need to use the Enthought build system? I’m trying to stick with conda/pip so I can make an installer for the environment.

**Comment by corranwebster** [comment]
Python 3.8 might be the issue - our production is on 3.6 and we aren't yet running CI tests on 3.8.

**Comment by danieljfarrell** [comment]
I got around to trying this with EDM.

    edm install -e "test-enable" --version 3.6
    edm install traitsui pyqt5 chaco
    edm shell -e test-enable
    python test.py

```python
# test.py
# Select QT5 or QT4
# https://github.com/enthought/traitsui/issues/407
import os
os.environ["ETS_TOOLKIT"] = "qt"
os.environ["QT_API"] = "pyqt5"
from enable.api import ComponentEditor
```

```python
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from enable.api import ComponentEditor
  File "C:\Users\daniel.farrell\.edm\envs\test-enable\lib\site-packages\enable\api.py", line 21, in <module>
    from .markers import MarkerTrait, marker_trait, MarkerNameDict, marker_names, \
  File "C:\Users\daniel.farrell\.edm\envs\test-enable\lib\site-packages\enable\markers.py", line 18, in <module>
    from .compiled_path import CompiledPath
  File "C:\Users\daniel.farrell\.edm\envs\test-enable\lib\site-packages\enable\compiled_path.py", line 17, in <module>
    from .toolkit import toolkit_object
  File "C:\Users\daniel.farrell\.edm\envs\test-enable\lib\site-packages\enable\toolkit.py", line 47, in <module>
    _init_toolkit()
  File "C:\Users\daniel.farrell\.edm\envs\test-enable\lib\site-packages\enable\toolkit.py", line 40, in _init_toolkit
    format_exception_only(t, v)))
ImportError: Unable to import the image backend for the qt toolkit (reason: ["ModuleNotFoundError: No module named 'enable.qt'\n"]).
```

However, if I uncomment the `os.envion` lines the import works!?

```python
# test2.py
# test.py
# Select QT5 or QT4
# https://github.com/enthought/traitsui/issues/407
# import os
# os.environ["ETS_TOOLKIT"] = "qt"
# os.environ["QT_API"] = "pyqt5"
from enable.api import ComponentEditor
```

**Comment by rkern** [comment]
> However you will likely need to set the ETS_TOOLKIT (or ETSConfig.toolkit) to 'qt4' rather than just 'qt' even when using Qt5 (ETS_TOOLKIT=qt works for TraitsUI, but I don't think Enable has been updated).

**Comment by danieljfarrell** [comment]
OK thanks for highlighting. I guess it’s not high in the priority list to update enable.
