### ISSUE TITLE
Some examples broken from not implementing _create_component

### ISSUE THREAD

**Issue by aaronayres35** [enthought/enable#500]
The demo currently located here https://github.com/enthought/enable/blob/2b3dbb7bae5b6e7946c4cbfaf90982c746da519a/examples/enable/canvas_demo.py, but soon to be moved by #494, currently does not run.

Trying to run the demo gives the following traceback:
<details>

```
$ python canvas_demo.py 
Traceback (most recent call last):
  File "canvas_demo.py", line 24, in <module>
    demo = demo_main(Demo, title="Canvas example")
  File "/Users/aayres/Desktop/enable/enable/example_support.py", line 49, in demo_main
    demo_class().configure_traits()
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traits/has_traits.py", line 2015, in configure_traits
    args,
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/toolkit.py", line 233, in view_application
    context, view, kind, handler, id, scrollable, args
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/view_application.py", line 84, in view_application
    context, view, kind, handler, id, scrollable, args
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/view_application.py", line 126, in __init__
    args=self.args,
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/view.py", line 462, in ui
    ui.ui(parent, kind)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/ui.py", line 244, in ui
    self.rebuild(self, parent)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/toolkit.py", line 163, in ui_live
    ui_live.ui_live(ui, parent)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/ui_live.py", line 43, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/ui_live.py", line 65, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/ui_base.py", line 286, in display_ui
    ui.owner.init(ui, parent, style)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/ui_live.py", line 225, in init
    self.add_contents(panel(ui), bbox)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 259, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 617, in __init__
    layout = self._add_items(content, inner)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 883, in _add_items
    ui, object, name, item.tooltip, None
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/editor_factory.py", line 132, in simple_editor
    description=description,
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/editor.py", line 459, in __init__
    self.old_value = getattr(self.object, self.name)
  File "/Users/aayres/Desktop/enable/enable/example_support.py", line 40, in _component_default
    return self._create_component()
  File "/Users/aayres/Desktop/enable/enable/example_support.py", line 45, in _create_component
    raise NotImplementedError
NotImplementedError
```

</details>

EDIT:
- [x] https://github.com/enthought/enable/blob/2b3dbb7bae5b6e7946c4cbfaf90982c746da519a/examples/enable/canvas_demo.py (#494)
- [ ] https://github.com/enthought/enable/blob/7b56e5275c707e7ee5749ce4ba141240729f5a26/examples/enable/shapes/run.py (#508)
- [ ] https://github.com/enthought/enable/blob/7b56e5275c707e7ee5749ce4ba141240729f5a26/examples/enable/tools/button_tool.py (#508)
- [ ] https://github.com/enthought/enable/blob/7b56e5275c707e7ee5749ce4ba141240729f5a26/examples/enable/tools/drop_tool.py (#508)

**Comment by aaronayres35** [comment]
Note a similar traceback is seen with: https://github.com/enthought/enable/blob/7b56e5275c707e7ee5749ce4ba141240729f5a26/examples/enable/shapes/run.py

<details>

```
$ python run.py 
Traceback (most recent call last):
  File "run.py", line 67, in <module>
    title="Click and drag the shapes")
  File "/Users/aayres/Desktop/enable/enable/example_support.py", line 49, in demo_main
    demo_class().configure_traits()
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traits/has_traits.py", line 2015, in configure_traits
    args,
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/toolkit.py", line 233, in view_application
    context, view, kind, handler, id, scrollable, args
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/view_application.py", line 84, in view_application
    context, view, kind, handler, id, scrollable, args
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/view_application.py", line 126, in __init__
    args=self.args,
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/view.py", line 462, in ui
    ui.ui(parent, kind)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/ui.py", line 244, in ui
    self.rebuild(self, parent)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/toolkit.py", line 163, in ui_live
    ui_live.ui_live(ui, parent)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/ui_live.py", line 43, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/ui_live.py", line 65, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/ui_base.py", line 286, in display_ui
    ui.owner.init(ui, parent, style)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/ui_live.py", line 225, in init
    self.add_contents(panel(ui), bbox)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 259, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 617, in __init__
    layout = self._add_items(content, inner)
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 883, in _add_items
    ui, object, name, item.tooltip, None
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/editor_factory.py", line 132, in simple_editor
    description=description,
  File "/Users/aayres/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/traitsui/editor.py", line 459, in __init__
    self.old_value = getattr(self.object, self.name)
  File "/Users/aayres/Desktop/enable/enable/example_support.py", line 40, in _component_default
    return self._create_component()
  File "/Users/aayres/Desktop/enable/enable/example_support.py", line 45, in _create_component
    raise NotImplementedError
NotImplementedError
```

</details>

**Comment by aaronayres35** [comment]
and also https://github.com/enthought/enable/blob/7b56e5275c707e7ee5749ce4ba141240729f5a26/examples/enable/tools/button_tool.py and https://github.com/enthought/enable/blob/7b56e5275c707e7ee5749ce4ba141240729f5a26/examples/enable/tools/drop_tool.py
