### ISSUE TITLE
Kiva Agg requires six but six is not mentioned as a runtime requirement

### ISSUE THREAD

**Issue by kitchoi** [enthought/enable#504]
The generated `kiva.agg.agg` module requires `six`:
https://github.com/enthought/enable/blob/6cf525cbeefdf34dc6eac5e54d7a73f755ea79b1/kiva/agg/src/graphics_context.i#L212-L215

But this dependency was not mentioned in the README nor in setup.py (e.g. extras_require).

**Comment by rahulporuri** [comment]
Looks like we missed this when working on removing python 2 support #415

**Comment by kitchoi** [comment]
For the record, this was uncovered by simply doing `pip install ` with the distribution in a clean Python environment and running the test suite shows this:
```
======================================================================
ERROR: kiva.tests.test_svg_drawing (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: kiva.tests.test_svg_drawing
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/kchoi/Work/ETS/enable/kiva/tests/test_svg_drawing.py", line 6, in <module>
    from kiva.svg import GraphicsContext
  File "/Users/kchoi/Work/ETS/enable/kiva/svg.py", line 55, in <module>
    from . import agg
  File "/Users/kchoi/Work/ETS/enable/kiva/agg/__init__.py", line 1, in <module>
    from .agg import *
  File "/Users/kchoi/Work/ETS/enable/kiva/agg/agg.py", line 722, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

In my experience, I think it is useful to ignore the tooling used by CI and just use `pip` for development.
