### ISSUE TITLE
gcbench fails on Windows

### ISSUE THREAD

**Issue by rahulporuri** [enthought/enable#670]
```
Benchmarking backend: svg
        Benchmark draw_image
        Benchmark draw_marker_at_points ... Failed
        Benchmark draw_path
        Benchmark draw_path_at_points
        Benchmark draw_rect
        Benchmark show_text ... Failed
Traceback (most recent call last):
  File "C:\Users\rporuri\.edm\envs\enable-test-3.6-pyqt5\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\rporuri\.edm\envs\enable-test-3.6-pyqt5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\rporuri\work\github\ets\enable\enable\gcbench\__main__.py", line 38, in <module>
    main()
  File "C:\Users\rporuri\work\github\ets\enable\enable\gcbench\__main__.py", line 34, in main
    publish(results, outdir)
  File "C:\Users\rporuri\work\github\ets\enable\enable\gcbench\publish.py", line 103, in publish
    fp.write(_INDEX_TEMPLATE.format(comparison_table=comparison_table))
  File "C:\Users\rporuri\.edm\envs\enable-test-3.6-pyqt5\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2718' in position 915: character maps to <undefined>
```

**Comment by rahulporuri** [comment]
Correction - It's not the SVG backend that's making gcbench fail. I commented out `svg` from the `_BACKENDS` dictionary and I still see the error. I commented out all of the `file` backends and I still see the error :|

**Comment by rahulporuri** [comment]
@jwiggins  looks like this got broken in #666.
