### ISSUE TITLE
Bleeding Edge Cron Job failure 

### ISSUE THREAD

**Issue by aaronayres35** [enthought/enable#866]
The most recent run of the bleeding-edge cron job failed with the following errors:
```
======================================================================
FAIL: test_save_dpi (kiva.tests.test_agg_drawing.TestAggDrawing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/kiva/tests/test_agg_drawing.py", line 24, in test_save_dpi
    self.assertEqual(self.save_and_return_dpi(), 144)
AssertionError: 143.99259999999998 != 144

======================================================================
FAIL: test_save_dpi (kiva.tests.test_celiagg_drawing.TestCeliaggDrawing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/kiva/tests/test_celiagg_drawing.py", line 22, in test_save_dpi
    self.assertEqual(self.save_and_return_dpi(), 144)
AssertionError: 143.99259999999998 != 144
```

**Comment by aaronayres35** [comment]
I find these failures very curious given these lines of code:
https://github.com/enthought/enable/blob/a33ea7bd6f96fdfb42765605edbb7f1f9e86f13a/kiva/agg/src/graphics_context.i#L909-L910
https://github.com/enthought/enable/blob/a33ea7bd6f96fdfb42765605edbb7f1f9e86f13a/kiva/celiagg.py#L897-L898

Need to investigate this more / track down what recent change in `traits`, `pyface` or `traitsui` could be related
