### ISSUE TITLE
Regression with locale tests on Windows/Wx

### ISSUE THREAD

**Issue by corranwebster** [enthought/enable#899]
We are now consistently getting this exception in Windows test with Wx:
```
======================================================================
ERROR: test_locale_independence (kiva.tests.agg.test_text.TestText)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\enable\enable\.edm\envs\enable-test-3.6-wx\lib\site-packages\kiva\tests\agg\test_text.py", line 47, in test_locale_independence
    x0, _ = gc.get_text_position()
  File "D:\a\enable\enable\.edm\envs\enable-test-3.6-wx\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "D:\a\enable\enable\.edm\envs\enable-test-3.6-wx\lib\site-packages\kiva\tests\agg\test_text.py", line 30, in locale_context
    locale.setlocale(category, old)
  File "D:\a\enable\enable\.edm\envs\enable-test-3.6-wx\lib\locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

----------------------------------------------------------------------
Ran 381 tests in 101.942s

FAILED (errors=1, skipped=62, expected failures=1)
```

This looks like there is some issue in setting the locale back to its original value (which shouldn't ever be a problem.

**Comment by corranwebster** [comment]
Investigating, it looks like this was previously being skipped because of a failure to set the locale on Windows (which is what I am seeing on a local VM). The initial setting is now succeeding but the reset is not.

Perhaps the fix is to try setting to the current setting to know we can get back?
